name: Generar cobrinha

on:
  schedule:
    - cron: "0 0 * * *"  # roda 1x por dia
  workflow_dispatch:     # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Guilherme450   # troque pelo seu usuário
          outputs: dist/github-snake.svg

      - name: Push GitHub Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
